---
  - hosts: localhost
    gather_facts: True
    vars_prompt:

    - name: nuxeoback
      prompt: Nuxeo backend private ip address
      default: nuxeoback
      private: no

    tasks: 
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }} and hostname.stdout
    - include: tasks/shibboleth.yml app=nuxeo
    - include: tasks/monit.yml app=nuxeo
    - name: create users directory
      file: path=~/users state=directory
    - name: placeholder user list so apache will start
      command: touch {{ role_home_dir.stdout }}/users/users.httpd.txt creates=~/users/users.httpd.txt
